### ISSUE TITLE
help_needed: Andy! help me: connecting Heroku to ghpages

### ISSUE THREAD

**Issue by farzaank** [amazingandyyy/mern#15]
## Describe the error/difficulties:
- ghpages keeps saying oops server error but we don't see any issues with heroku

## What have you done:
- looked at the heroku logs and saw that we needed to add jwt secret but even after that gh pages fails to work

here's our github
https://github.com/codethechange/codethechange.konexio-mern-stack

here's the ghpage
https://codethechange.github.io/codethechange.konexio-mern-stack/

here's the heroku server
https://konexio-server.herokuapp.com/

**Comment by amazingandyyy** [comment]
@farzaank sorry I just see this thread, what did you see in the logs

![Screen Shot 2019-05-29 at 11 10 06 AM](https://user-images.githubusercontent.com/7886068/58580600-5b035000-8202-11e9-8bf9-7dd32e46c58a.png)

**Comment by amazingandyyy** [comment]
don't forget to add `mongoLab` plugin in the Resources tab. 

![Screen Shot 2019-05-29 at 11 11 10 AM](https://user-images.githubusercontent.com/7886068/58580667-7d956900-8202-11e9-9f74-a8ac72a5ebb4.png)

**Comment by farzaank** [comment]
We did add mLab to heroku. I looked at the logs to see this:
<img width="1206" alt="Screen Shot 2019-05-29 at 1 57 53 PM" src="https://user-images.githubusercontent.com/39839866/58590830-d7555d80-8219-11e9-93d1-61d898513f74.png">
<img width="802" alt="Screen Shot 2019-05-29 at 1 57 09 PM" src="https://user-images.githubusercontent.com/39839866/58590831-d7edf400-8219-11e9-988e-781ab44664ac.png">
So maybe our jwt secret isn't working? How should we add it: through our git repo, or through the console on Heroku? I tried to do the latter but it appears the JWT secret is still missing?

**Comment by amazingandyyy** [comment]
I see you need to create JWT_SECRET in heroku dashboard: settings>Config Vars>Reveal Config Vars

**Comment by amazingandyyy** [comment]
don't put `.env` to git/heroku :)

**Comment by farzaank** [comment]
makes sense, thanks! i'll close this if the problem stops after adding the JWT_SECRET

**Comment by farzaank** [comment]
added the JWT_SECRET but the problem is persisting on our GH_pages site. Here are the heroku logs. Do you think we are missing something in the client?
<img width="799" alt="Screen Shot 2019-05-29 at 5 09 35 PM" src="https://user-images.githubusercontent.com/39839866/58599323-a0d90c00-8234-11e9-85a7-a6b3076e8dac.png">

**Comment by amazingandyyy** [comment]
What’s the error for the gh_pages?

**Comment by farzaank** [comment]
it's just oops server error
<img width="888" alt="Screen Shot 2019-05-30 at 6 39 42 PM" src="https://user-images.githubusercontent.com/39839866/58675706-54f89680-830a-11e9-89eb-ee989c90ab58.png">

**Comment by farzaank** [comment]
i just tried a bunch of random things. I'm not sure exactly what I did to fix it. but it's working now. i think the issue was i was working on two separate branches and merging them fixed it

**Comment by amazingandyyy** [comment]
Awesome! Glad to hear that! Let me know if any further questions you have, few free to reopen or open a new issues! Cheers!
