### ISSUE TITLE
help_needed: Andy! help me:

### ISSUE THREAD

**Issue by evgenij1987** [amazingandyyy/mern#16]
Hi Andy,
thanks for the boilerplate, which is really helpful.
I have a question regarding the boilerplate. Is there any reason behind the fact that api/authentication.js and user/controller.js contain identical code?

Wouldn't it be reasonable two have everything in one place?

**Comment by amazingandyyy** [comment]
@evgenij1987 good point, I remove signup/signin under user/controller.js and remove updateProfile under api/authentication.js

Good catch! and thanks for using and reaching out :)
