### ISSUE TITLE
NPM_CONFIG_PRODUCTION problem

### ISSUE THREAD

**Issue by gakeko2018** [amazingandyyy/mern#17]
Hi thanks for the repo.
when I run "npm i" I get this error:
'NPM_CONFIG_PRODUCTION' is not recognized as an internal or external command,

**Comment by Marlin005** [comment]
> Hi thanks for the repo.
> when I run "npm i" I get this error:
> 'NPM_CONFIG_PRODUCTION' is not recognized as an internal or external command,

Hi! I had the same error when I launched the team "npm run build" on server. Did you manage to solve it?

**Comment by amazingandyyy** [comment]
@gakeko2018 @Marlin005 

Hi Thanks for the reporting, it because you are in the windows environment, I update the code, so it works for you now, please pull from the original repo again.

```shell
git remote add upstream git@github.com:amazingandyyy/mern.git
git pull upstream master
```

if you

**Comment by amazingandyyy** [comment]
please feel free to reopen an issue if it still doesn't for you, and again, thanks for using this project :D

**Comment by Marlin005** [comment]
> @gakeko2018 @Marlin005
> 
> Hi Thanks for the reporting, it because you are in the windows environment, I update the code, so it works for you now, please pull from the original repo again.
> 
> you can now do the following to pull the latest updates
> 
> ```shell
> git remote add upstream git@github.com:amazingandyyy/mern.git
> git pull upstream master
> ```

Thanks for the quick contact! Yes, I ran in the windows enviroment  and there were also problems on the client with launch "npm run build". After installation cygwin it worked. 

These configuration variables "NPM_CONFIG_PRODUCTION" are necessary for the platform, as I understand it.  So I installed Heroku CLI.

**Comment by amazingandyyy** [comment]
glad it works, let me know if anything doesn't work on windows!
