### ISSUE TITLE
help_needed: Andy! help me: HEROKU

### ISSUE THREAD

**Issue by Rasul975** [amazingandyyy/mern#18]
## Describe the error/difficulties:
- Error: No JWT_SECRET in env variable, check instructions: https://github.com/amazingandyyy/mern#prepare-your-secret

-  I GET THIS WHEN I TRY LOGIN FROM github pages and heroku IN THE CONSOLE.  Access to XMLHttpRequest at 'https://unique-mern.herokuapp.com/signin' from origin 'https://rasul975.github.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

## What have you done:
- added .env in server/src/.env,
- added JWT_SECRET and VALUE "mongodb+srv://<username>:<password>@uniquealterations-khlsn.mongodb.net/test?retryWrites=true&w=majority"

MONGODB_URI=mongodb+srv://<username>:<password>@<test>.mongodb.net/test?retryWrites=true&w=majority

## What it supports to do?
- connect to mongoDb remote servers

**Comment by amazingandyyy** [comment]
I am looking at it!
