### ISSUE TITLE
Deprecate body-parser and use express.json() instead

### ISSUE THREAD

**Issue by amazingandyyy** [amazingandyyy/mern#23]
## Describe the error/difficulties:
- body-parser is deprecated, use `express.json()` middleware instead.

## What it supports to do?
- Deprecate body-parser and use express.json() instead

**Comment by shikhar13012001** [comment]
Can I work on this issue?
@amazingandyyy

**Comment by archit2216** [comment]
@amazingandyyy by body-parser is deprecated it means that the body-parser contructor is deprecated
that is: app.use(bodyParser()) is deprecated now

But we now need to call these 2 methods separately:
app.use(bodyParser.urlencoded());
app.use(bodyParser.json());

If you get a warning related to urlEncoding, you need to do:
app.use(bodyParser.urlencoded({
  extended: true
}));

**Comment by amazingandyyy** [comment]
Thanks to @AMJasser this issue is now resolved!

**Comment by amazingandyyy** [comment]
@shikhar13012001  sorry I just see your message, let me know what else you want to contribute!

**Comment by amazingandyyy** [comment]
@archit2216 thanks for the details!
