### ISSUE TITLE
Error with command: npm i

### ISSUE THREAD

**Issue by mohamedmehdigara** [amazingandyyy/mern#26]
## Describe the error/difficulties:
- 
npm ERR! code E401
npm ERR! Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2022-02-01T07_21_06_615Z-debug.log
## What have you done:
npm i

## What it supports to do?
-

**Comment by CharingJC** [comment]
please rmv the dependency named github hooks

**Comment by mohamedmehdigara** [comment]
Hello. In which file is the dependency named github hooks located and if possible in which line please.

**Comment by archit2216** [comment]
@mohamedmehdigara git hooks is located between line no. 7 to 12 in the package-lock.json
U also need to remove the git hooks dependency from line number 32 in package.json.

**Comment by amazingandyyy** [comment]
I will create a PR to fix it

**Comment by amazingandyyy** [comment]
fixed, please clone again or pull main branch
